---
BaseUrl: "http://blog.ralch.com"
LanguageCode: "en-us"
Title: "Svetlin Ralchev"
Theme: "PaperMod"

Paginate: 5
EnableInlineShortcodes: true
EnableRobotsTXT: true
BuildDrafts: false
buildFuture: false
buildExpired: false
EnableEmoji: true

GoogleAnalytics: "UA-62134307-2"

Params:
  Author: "Svetlin Ralchev"

  SocialIcons:
    - name: "linkedin"
      url: "http://uk.linkedin.com/in/ralchev"
    - name: "twitter"
      url: "https://twitter.com/ralch"
    - name: "github"
      url: "https://github.com/iamralch"
    - name: "website"
      url: "https://www.ralch.com"
    - name: "rss"
      url: "index.xml"

  HomeInfoParams:
    Title: Hello World!
    Content: git clone https://github.com/iamralch/whoami

  Env: production
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

menu:
  main:
   - name: Archive
     url: archives
     weight: 5
   - name: Tags
     url: tags/
     weight: 10
   - name: Categories
     url: categories/
     weight: 10
