---
BaseUrl: "http://blog.ralch.com"
GoogleAnalytics: "UA-62134307-2"

Theme: "PaperMod"
LanguageCode: "en-us"

Title: "Svetlin Ralchev | Blog"
Copyright: "(c) 2023 Svetlin Ralchev"

BuildDrafts: false
BuildExpired: false
BuildFuture: false
EnableEmoji: true
EnableInlineShortcodes: true
EnableRobotsTXT: true
Paginate: 5

Params:
  Author: "Svetlin Ralchev"

  Label:
    text: "Svetlin Ralchev"
    icon: "/logo.png"
    iconHeight: 35

  SocialIcons:
    - name: "linkedin"
      url: "http://uk.linkedin.com/in/ralchev"
    - name: "twitter"
      url: "https://twitter.com/ralch"
    - name: "github"
      url: "https://github.com/iamralch"
    - name: "website"
      url: "https://www.ralch.com"
    - name: "rss"
      url: "index.xml"

  HomeInfoParams:
    Title: Hello World! Golang, Microservices, DevOps!
    Content: "`git clone https://github.com/iamralch/whoami`"

  Env: production

  ShowToc: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  DisableThemeToggle: true

menu:
  main:
    - name: Archive
      url: archives
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: Categories
      url: categories/
      weight: 20
