#!/bin/bash -ex

[ -z "$DEBUG" ] || set -x

SOURCE="$(PWD)"
BLOG_CONFIG="$SOURCE/config.yaml"
DESTINATION="$(mktemp -d)"
THEME_NAME="kube"
BASE_URL="http://blog.ralch.com"

main() {
  generate_blog
  prepare_output
}


generate_blog() {
  hugo --source "$SOURCE"  --destination "$DESTINATION" --config "$BLOG_CONFIG" --theme "$THEME_NAME" --baseURL "$BASE_URL"
}

prepare_output() {
  cp -rv "$DESTINATION/." "$PWD/../ralch.github.io"
}

main
