#!/bin/bash -e

NAME="$1"
APP_NAME="$0"

[ -z "$DEBUG" ] || set -x
[ -z "$NAME" ] && fail "Usage: $APP_NAME [article-name]"

new_article() {
  local name
  name="$1"
  hugo new articles/"$name".md -k yaml
}

fail() {
  echo "$*"
  exit 1
}

new_article "$NAME"
